Added support for dependency destination specification. (Resolves #1038)
yonaskolb/XcodeGen pull request #1039
Opened 2021-03-23 21:13 UTC by JakubBednar

2021-03-24 03:23 UTC, freddi-kit reviewed
Hello, @JakubBednar. Before submitting a pull request, please add a test to it. Please refer to the test topic in CONTRIBUTING.md https://github.com/yonaskolb/XcodeGen/blob/master/CONTRIBUTING.md#tests

2021-03-24 08:12 UTC, JakubBednar commented
Hello, frankly it is harder for me to navigate your unit-tests than to update the actual code and add the feature. :) So I was hopping to get a general feedback on the proposed feature and solution first. If you'd agree that this is something that makes sense to you and the proposed way of implementation is correct as well I will add the tests. But if you decide that you do not want this feature or you want it implemented differently than I would be just wasting my time on the tests.

With that said, I suppose I should extend both ProjectSpecTests and PBXProjGeneratorTests. Or is there anything else?

2021-03-25 12:24 UTC, JakubBednar commented on Tests/XcodeGenKitTests/ProjectGeneratorTests.swift
> +                            Dependency(type: .target, reference: appA.name, embed: true),
There are several target types that original XcodeGen was not embedding even when embed was set to true. Or maybe it puts them into different sections than copyFiles section? I am not sure and I have not found any tests describing original embedding scheme for different types of dependencies

2021-03-31 18:19 UTC, freddi-kit commented
Thank you for your update and I'm sorry for my late reply. Now I became Collaborator for this repo so please give a time to learn and I'll review it soon!

2021-04-02 18:09 UTC, freddi-kit commented on Sources/XcodeGenKit/PBXProjGenerator.swift
> +                guard let destination = phase.destination.destination else { continue }
FYI: I had a same opinion at here https://github.com/yonaskolb/XcodeGen/pull/796#discussion_r388317066 and it is accepted, so I think what you write is okay :)

2021-05-10 07:08 UTC, JakubBednar commented
Hello, @freddi-kit. Anything I can do to make this get merged?

2021-06-29 08:22 UTC, jakubkiermasz-zd commented
Hello!
Seems like this resolves #1102, doesn't it :)?

@JakubBednar, @freddi-kit any updates?

2021-06-29 12:39 UTC, jakubkiermasz-zd commented
If you are interested, https://github.com/zendesk/XcodeGen is the fork aligned with the develop that we will use till it's merged.

2021-06-30 06:29 UTC, yonaskolb commented
Thanks for the great work here @JakubBednar. It all seems good. Only thing is I'm a little hesitant to merge 1700 lines of testing code that will have to be maintained. If you can reduce this a bit with the use of some helper functions or some setup objects that would be great. Once done and the conflicts are resolved, we can get this merged 👍 

@jakubkiermasz-zd are you confirming this solves your particular use case?

2021-06-30 06:59 UTC, freddi-kit commented
Ah sorry for not adding comments for a long time, I thought I asked others to review but it looks ask review button in github not works when I tapping, sorry. 🙇

2021-06-30 08:47 UTC, jakubkiermasz-zd commented
@yonaskolb I am. It works like a charm ^^

2021-07-13 16:38 UTC, JakubBednar commented
I have resolved the conflicts and remove IMO the only boiler-plate code in the unit-tests. Please note the following about the unittests:

1. I did cover all available dependency types and there is a lot of it
2. For each dependency type, the first test actually fixes how xcodegen worked before changes. For some dependency types it ignored `embed: true` for some it ignored `embed: false`. For bundle dependencies it still does as these seem to take different path in the code and I was not sure whether it was an intention or a bug so I did not change it.

2021-07-15 02:06 UTC, yonaskolb commented on CHANGELOG.md
> +- Allow specifying a `copy` setting for each dependency. [#1038](https://github.com/yonaskolb/XcodeGen/pull/1039) @JakubBednar
Can we move this up into `Next Version`

2021-07-15 02:07 UTC, yonaskolb requested changes
Great, thank you @JakubBednar

2021-07-15 02:10 UTC, merged